# Generated by Django 4.1.4 on 2023-01-05 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_prn', models.CharField(max_length=15)),
                ('stud_name', models.CharField(max_length=25)),
                ('stud_div', models.CharField(max_length=25)),
                ('stud_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='mutiple_image_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_images', models.ImageField(upload_to='train')),
                ('train_input_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewapp.student_data')),
            ],
        ),
    ]
