# Generated by Django 4.1.4 on 2023-01-05 15:16

from django.db import migrations, models
import reviewapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutiple_image_upload',
            name='train_images',
            field=models.ImageField(upload_to=reviewapp.models.update_filename),
        ),
    ]
